@startuml

class Familia {
    id: integer
    nome: string
    gestor: Gestor
    familiares: Familiar[]
}

class Familiar {
    id: integer
    nome: string
}

class Gestor {
    adicionarFamiliar(familiar: Familiar)
}

class InstituicaoFinanceira {
    codigo: int
    conta: int
    urlAPI: string
}

class Objetivo {
    id: integer
    nome: string
    valorAlvo: float
    dataAlvo: date
    tipo: string
}

class Transacao {
    id: integer
    descricao: string
    valor: float
    data: date
    tipo: string
}

Familia -- Familiar : pertence
Familiar -- Gestor : gere
Familiar -right- Objetivo : tem
Familiar -left- Transacao : faz
InstituicaoFinanceira -- Familiar : conecta

@enduml
